In [21]:
#Name: Prajwal Mhase
#Roll No: 93
#Batch: T1B
#Assignment Title: Assignment 1
#Date: 01/08/2025

In [22]:
import numpy as np

In [23]:
#initializing arrays
#1D array
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print("Array 1: \n",arr1)
#2D array
arr2=np.array([[11,12,13,],[14,15,16],[17,18,19]])
print("\n Array 2: \n",arr2)

Array 1: 
 [ 1  2  3  4  5  6  7  8  9 10]

 Array 2: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [24]:
#Array attributes

print("Array 1 Shape:",arr1.shape)
print("Array 2 Shape:",arr2.shape)

print("\nArray 1 Data type:",arr1.dtype)
print("Array 2 Data type:",arr2.dtype)


Array 1 Shape: (10,)
Array 2 Shape: (3, 3)

Array 1 Data type: int64
Array 2 Data type: int64


In [25]:
#Array Indexing
print("\nElement at index 0 in Array 1:", arr1[0])
print("Element at index 1,2 in Array 2:", arr2[1,2])

#Array Slicing
print("\nSlicing Array 1 from index 2 to 5:", arr1[2:6])
print("Slicing Array 2 from index 0 to 1 and 1 to 2:\n", arr2[0:2, 1:3])



Element at index 0 in Array 1: 1
Element at index 1,2 in Array 2: 16

Slicing Array 1 from index 2 to 5: [3 4 5 6]
Slicing Array 2 from index 0 to 1 and 1 to 2:
 [[12 13]
 [15 16]]


In [26]:
#Array Arrange
arr3 = np.arange(20,31,2)
print("Array 3:",arr3)

#Array Reshape
arr4 = arr3.reshape(2,3)
print("Array 4 (Reshaped Array 3):\n", arr4)

Array 3: [20 22 24 26 28 30]
Array 4 (Reshaped Array 3):
 [[20 22 24]
 [26 28 30]]


In [27]:
#Arrithmetic Operations
print("\nArray 1 + Array 2:", arr1[:3]+arr2[0]) #Addition
print("Array 1 - Array 2:", arr1[:3]-arr2[0]) #Subtraction
print("Array 1 * Array 2:", arr1[:3]*arr2[0]) #Multiplication
print("Array 1 / Array 2:", arr1[:3]/arr2[0]) #Division
print("Array 1 % Array 2:", arr1[:3]%arr2[0]) #Modulus
print("Array 1 ** Array 2:", arr1[:3]**arr2[0]) #Exponentiation
print("Array 1 // Array 2:", arr1[:3]//arr2[0]) #Floor Division
print("Array 1 @ Array 2:", arr1[:3]@arr2[0]) #Matrix Multiplication
print("Array 1 == Array 2:", arr1[:3]==arr2[0]) #Equality Check
print("Array 1 != Array 2:", arr1[:3]!=arr2[0]) #Inequality Check 
print("Array 1 < Array 2:", arr1[:3]<arr2[0]) #Less Than Check
print("Array 1 <= Array 2:", arr1[:3]<=arr2[0]) #Less Than or Equal To Check  
print("Array 1 > Array 2:", arr1[:3]>arr2[0]) #Greater Than Check
print("Array 1 >= Array 2:", arr1[:3]>=arr2[0]) #Greater Than or Equal To Check
print("Array 1 & Array 2:", arr1[:3]&arr2[0]) #Bitwise AND
print("Array 1 | Array 2:", arr1[:3]|arr2[0]) #Bitwise OR
print("Array 1 ^ Array 2:", arr1[:3]^arr2[0]) #Bitwise XOR
print("Array 1 ~ Array 2:", ~arr1[:3]) #Bitwise NOT
print("Array 1 << Array 2:", arr1[:3]<<arr2[0]) #Left Shift
print("Array 1 >> Array 2:", arr1[:3]>>arr2[0]) #Right Shift


Array 1 + Array 2: [12 14 16]
Array 1 - Array 2: [-10 -10 -10]
Array 1 * Array 2: [11 24 39]
Array 1 / Array 2: [0.09090909 0.16666667 0.23076923]
Array 1 % Array 2: [1 2 3]
Array 1 ** Array 2: [      1    4096 1594323]
Array 1 // Array 2: [0 0 0]
Array 1 @ Array 2: 74
Array 1 == Array 2: [False False False]
Array 1 != Array 2: [ True  True  True]
Array 1 < Array 2: [ True  True  True]
Array 1 <= Array 2: [ True  True  True]
Array 1 > Array 2: [False False False]
Array 1 >= Array 2: [False False False]
Array 1 & Array 2: [1 0 1]
Array 1 | Array 2: [11 14 15]
Array 1 ^ Array 2: [10 14 14]
Array 1 ~ Array 2: [-2 -3 -4]
Array 1 << Array 2: [ 2048  8192 24576]
Array 1 >> Array 2: [0 0 0]


In [28]:
#Self Learning Topics
#Argmax
print("\nArgmax of Array 1:", np.argmax(arr1))
print("Argmax of Array 2:", np.argmax(arr2))

#Argmin
print("\nArgmin of Array 1:", np.argmin(arr1))
print("Argmin of Array 2:", np.argmin(arr2))

#Linespace
print("\nLinspace from 0 to 10 with 5 points:", np.linspace(0,10,5))

#Difference
print("\nDifference of Array 1:", np.diff(arr2))



Argmax of Array 1: 9
Argmax of Array 2: 8

Argmin of Array 1: 0
Argmin of Array 2: 0

Linspace from 0 to 10 with 5 points: [ 0.   2.5  5.   7.5 10. ]

Difference of Array 1: [[1 1]
 [1 1]
 [1 1]]


In [29]:
?arr2

Type:        ndarray
String form:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
Length:      3
File:        c:\users\prajw\appdata\roaming\python\python313\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
d