In [1]:
import numpy as np
import pandas as pd

In [ ]:
a=np.zeros(5)
print(a,a.dtype)
b=a.astype(np.int32)
print(b,b.dtype)

[0. 0. 0. 0. 0.] float64
[0 0 0 0 0] int32


In [3]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2]])
print(c,c.shape,c.dtype)



[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]] (3, 4) int64


In [10]:
arr=np.array([1,10,5,8])
print(np.swapaxes(c,0,1),"\n")
print(arr.max(),"\n")
print(arr.reshape((2,2)),"\n")
print(np.linspace(0,4,5,dtype=int),"\n")
print(np.sort(arr),"\n")

[[1 5 9]
 [2 6 0]
 [3 7 1]
 [4 8 2]] 

10 

[[ 1 10]
 [ 5  8]] 

[0 1 2 3 4] 

[ 1  5  8 10] 

